apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: 'botofchat'
  janus-idp.io/tekton: 'botofchat'
  backstage.io/kubernetes-id: 'botofchat'
  backstage.io/kubernetes-namespace: 'rhdh-app'
  app.kubernetes.io/part-of: 'botofchat'
resources:
  - application-dev.yaml
