kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'botofchat-imagestream-job-rolebinding'
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: 'botofchat-dsp-job'
    namespace: 'rhdh-app'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'botofchat-imagestream-job-role'
