apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: 'botofchat'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 'botofchat'
  name: 'botofchat'
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
