apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: 'botofchat'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 'botofchat'
  name: 'botofchat'
spec:
  ports:
    - port: '8501'
      protocol: TCP
      targetPort: '8501'
  selector:
    app.kubernetes.io/instance: 'botofchat'
