apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: 'botofchat-model-server'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 'botofchat-model-server'
  name: 'botofchat-model-server'
spec:
  ports:
    - port: '8001'
      protocol: TCP
      targetPort: '8001'
  selector:
    app.kubernetes.io/instance: 'botofchat-model-server'
